# Generated by Django 4.0 on 2021-12-22 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_entry_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='entry_year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)], verbose_name='Год поступления'),
        ),
    ]
