# Generated by Django 4.0 on 2021-12-29 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expr', models.CharField(help_text='Введите выражение', max_length=255, verbose_name='Выражение')),
                ('result', models.FloatField(help_text='Введите ожидаемый результат', verbose_name='Результат')),
                ('actual_result', models.FloatField(verbose_name='Истинный результат')),
                ('is_valid', models.BooleanField(blank=True, default=False, verbose_name='Ответ правильный')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expressions', to='users.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Выражение',
                'verbose_name_plural': 'Выражения',
            },
        ),
    ]
